/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicVerifyRouteImport } from './routes/api/public/verify'
import { Route as ApiPublicAssetRouteImport } from './routes/api/public/asset'
import { Route as ApiAdminUploadFileRouteImport } from './routes/api/admin/upload-file'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicVerifyRoute = ApiPublicVerifyRouteImport.update({
  id: '/api/public/verify',
  path: '/api/public/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAssetRoute = ApiPublicAssetRouteImport.update({
  id: '/api/public/asset',
  path: '/api/public/asset',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminUploadFileRoute = ApiAdminUploadFileRouteImport.update({
  id: '/api/admin/upload-file',
  path: '/api/admin/upload-file',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/api/admin/upload-file': typeof ApiAdminUploadFileRoute
  '/api/public/asset': typeof ApiPublicAssetRoute
  '/api/public/verify': typeof ApiPublicVerifyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/api/admin/upload-file': typeof ApiAdminUploadFileRoute
  '/api/public/asset': typeof ApiPublicAssetRoute
  '/api/public/verify': typeof ApiPublicVerifyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/api/admin/upload-file': typeof ApiAdminUploadFileRoute
  '/api/public/asset': typeof ApiPublicAssetRoute
  '/api/public/verify': typeof ApiPublicVerifyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/api/admin/upload-file'
    | '/api/public/asset'
    | '/api/public/verify'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/api/admin/upload-file'
    | '/api/public/asset'
    | '/api/public/verify'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/api/admin/upload-file'
    | '/api/public/asset'
    | '/api/public/verify'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  ApiAdminUploadFileRoute: typeof ApiAdminUploadFileRoute
  ApiPublicAssetRoute: typeof ApiPublicAssetRoute
  ApiPublicVerifyRoute: typeof ApiPublicVerifyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/verify': {
      id: '/api/public/verify'
      path: '/api/public/verify'
      fullPath: '/api/public/verify'
      preLoaderRoute: typeof ApiPublicVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/asset': {
      id: '/api/public/asset'
      path: '/api/public/asset'
      fullPath: '/api/public/asset'
      preLoaderRoute: typeof ApiPublicAssetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/upload-file': {
      id: '/api/admin/upload-file'
      path: '/api/admin/upload-file'
      fullPath: '/api/admin/upload-file'
      preLoaderRoute: typeof ApiAdminUploadFileRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  ApiAdminUploadFileRoute: ApiAdminUploadFileRoute,
  ApiPublicAssetRoute: ApiPublicAssetRoute,
  ApiPublicVerifyRoute: ApiPublicVerifyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
